### ISSUE TITLE
但凡给这玩意儿贡献一点代码的，都是在糟践开源软件精神。

### ISSUE THREAD

**Issue by MGLSUDE** [fenwii/OpenHarmony#2]
都是在糟蹋践踏开源精神。

**Comment by fenwii** [comment]
看你库里什么都没有，不太好评论你的这句话，多写点代码比评论强。

**Comment by MGLSUDE** [comment]
> 看你库里什么都没有，不太好评论你的这句话，多写点代码比评论强。

差不多得了吧，你不也这样。拿仓库当你网站主页，鬼知道你那套东西是从哪里抄来的。

**Comment by fenwii** [comment]
都开源了，没有必要抄，好好写代码就行

**Comment by MGLSUDE** [comment]
> 都开源了，没有必要抄，好好写代码就行

有人是不懂Z治和基本的用户隐私还有自由原则啊，鸿蒙这个东西要让开发者实名认证，以及让用户只能装备案的应用。这不是在践踏原则是在什么。现在程序员基本缺乏当年自由软件社区是怎么对bom标准警惕的技术与Z治警惕性

**Comment by MGLSUDE** [comment]
> 都开源了，没有必要抄，好好写代码就行

而且所有 It行业从业者应该明白自己干的这行就是跟上面对着干的，跟上面是个死敌。不是你弄死他们，就是他们弄死你。

**Comment by MGLSUDE** [comment]
> 看你库里什么都没有，不太好评论你的这句话，多写点代码比评论强。

在赛里斯这个搞政治的地方，不会玩政治就等着被整吧。尤其是开源这种在赛比斯明显属于政治话题的东西。
